### DISCUSSION TITLE
[Model] lightGBM 모델을 활용한 랭킹화

### DISCUSSION THREAD

**Discussion by ds-wook** [lunch-corp/yamyam-lab#59] [Problems to solve]
feature store 구축에 대한 디스커션입니다. 아이디어 있으면 제가 여기에다 남길게요

**Comment by LearningnRunning** [comment]
리뷰어의 활용하기 좋은 feature로 badge_level, date_scaled, score_scaled을 쓰면 어떨까요? score_scaled는 y값에 관여된 것이라 힘들 것 같지만 
date_scaled랑 badge_level는 좋을 거 같아요!

date_scaled: 가장 최근 크롤링 날짜 기준 과거일 수록 낮은 값, 단 3개월까지는 같은 가중치를 min-max Scale한 feature(score_range=(-0.5, 1.0))
score_scaled: 각 리뷰별 reviewer_review_score - reviewer_review_avg 이후 min-max Scale한 feature (score_range: 0.01 ~ 1.0)
badge_level: 1~ 100으로 된 값인데 0.01을 곱하면 score_scaled와 score_range가 똑같이 매겨져 사용 가능

**Reply by ds-wook** [reply]
네 실험해보겠습니다

**Comment by bohyunshin** [comment]
리뷰어별로 훈련 데이터에서 각 식당 범주를 방문한 횟수를 피쳐로 넣는 것은 어떨까요?
예를 들어서 a라는 유저가 훈련 데이터에서 한식 음식점 1회, 중식 음식점 2회를 방문했으면 그걸 넣는 거죠. 아니면 방문 횟수가 아니라 평균 평점으로 해도 되겠네요. 근데 이미 넣고 계실 것 같다는 생각이 들기도 하네요 ㅎㅎ

**Reply by ds-wook** [reply]
좋은 의견 감사합니다. 생각해보지 못했던 방법이라 괜찮은 방법 같아요!

**Comment by bohyunshin** [comment]
@ds-wook @LearningnRunning 
https://www.youtube.com/watch?v=zRLS3_vD1FM
9분00초에 위도/경도를 범주화해서 피쳐로 넣는 방법이 나오는데요. 이거 예전에 성록님이 말씀하셨었나요?? 적용해보면 좋을 것 같네요.
저도 뭔가 저거를 적용할 수 있는 방법이 있을지 고민해볼게요 ㅋㅋ
배달의 민족이 locality을 고려한 서비스를 하다보니까, 저희와 결이 비슷한 것 같긴해요

**Reply by ds-wook** [reply]
오 좋은거 같아요 한번 시도해볼수 있을거 같아요

**Comment by bohyunshin** [comment]
@ds-wook 
https://github.com/sidewalklabs/s2sphere
참고하세요 ㅎㅎ 이거 한번 사용해보려구요

**Comment by bohyunshin** [comment]
@ds-wook 
https://www.youtube.com/watch?v=Ub1kL0OB5n8
이것도 배민에서 발표한 내용인데 지역 클러스터링 관련 내용이거든요?! 이 발표자는 google s2가 아니라 uber h3를 썼어요.
https://github.com/uber/h3-py
먼가 이게 공식 파이썬 라이브러리도 나와있어서 좀 더 신뢰가 가는 것 같네요 ㅎ

**Reply by ds-wook** [reply]
h3 라이브러리 보고 있는데 기능도 다양하고 이 라이브러리에서도 근처 지역까지 뽑아주는 메소드가 있는거 같아요ㅎㅎ
보현님께서도 참고해보시면 좋을거 같아요
https://uber.github.io/h3-py/api_comparison.html

**Reply by bohyunshin** [reply]
@ds-wook 님,
오 네네 이미 몇개 사용하고 있긴한데,

* https://github.com/LearningnRunning/yamyam-lab/blob/main/src/tools/h3.py

참고하겠습니다~

**Comment by ds-wook** [comment]
@bohyunshin @LearningnRunning 
![image](https://github.com/user-attachments/assets/99b50695-4733-42be-84eb-291394233a23)

lightgbm feature를 학습한 내용입니다.
y는 제가 맛집인지 아닌지를 분류한 이진 인코딩 feature이며
X는 아래와 같습니다.
```yaml
features:
  - badge_level: 뱃지 레벨
  - badge_grade: 뱃지 점수
  - date_scaled: 성록님께서 만드신 시간 지표
  - date_weight: 성록님께서 만드신 시간 지표
  - diner_review_cnt_category: all_review_cnt의 범주화 feature
  - min_price: 메뉴의 최소 가격
  - max_price: 메뉴의 최대 가격
  - mean_price: 메뉴의 평균 가격
  - median_price: 메뉴의 중앙값 가격
  - menu_count: 메뉴 개수
  - taste: 맛 지수
  - kind: 친절 지수
  - mood: 분위기 지수
  - chip: 가성비 지수
  - parking: 주차 지수

cat_features:
  - diner_review_cnt_category
  - badge_level
  - badge_grade
```
diner_review_cnt_category같은 경우 all_review_cnt를 범주화하여 넣어줬습니다. 제가 all_review_cnt를 사용했던걸 까먹었습니다. 공유드리지 못한점 죄송합니다. 또한 lightgbm은 자체 내장 알고리즘에 categorical feature를 따로 처리하여 학습을 해줍니다. 해당 파라미터 설정은 아래와 같이 하였습니다.
